podTemplate(yaml: '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: sonar
    image: sonarsource/sonar-scanner-cli
    command:
    - sleep
    args:
    - infinity
  - name: python
    image: python:3.12
    command:
    - sleep
    args:
    - infinity
''') {
    node(POD_LABEL) {
       container('sonar'){
        checkout scm
        withSonarQubeEnv('ElSonarDeMiEmpresa'){
            sh "sonarsource/sonar-scanner-cli"
        }
        timeout(time: 1, unit: 'HOURS') {
            waitForQualityGate abortPipeline: true
        }            
       }
       container('python'){
        sh 'RUN pip install --no-cache-dir -r devops/requirements.txt'
        sh 'bin/ejecutar_pruebas.sh'
       }
    }
}
